import Head from 'next/head'
import Image from 'next/image'
import NavBar from './components/NavBar'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Subscribe to VolleyConnect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="col-md-8">
      <main className={styles.main}>
        <NavBar />
        <h1 className={styles.gradientText} id={styles.title}>Your Source for Volleyball</h1>
        <h2>Professional Volleyball stories, news and information from the Insiders who make it happen</h2>
        <div className={styles.grid}>
          <a
            href="https://volleyconnect.ghost.io/bic"
            className={styles.card}
          >
            <h2>Get your $1 premium account &rarr;</h2>
            <p>
                To celebrate our launch we are giving you a premium accounts for just <strong>$1!</strong>
            </p>
          </a>
          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Read your favorite Player's Stories &rarr;</h2>
            <p>Exclusive pieces, as told by the athletes</p>
          </a>
          <a href="#" className={styles.card}>
            <h2><strong>Learn all about Agents &rarr;</strong></h2>
            <p>The secrets to how Agencies work</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Learn about Professional Volleyball &rarr;</h2>
            <p>Discover what it takes to become a pro</p>
          </a>
        </div>
        <div className={styles.spacing}>
          <h2></h2>
          <p className={styles.description}>
            We know that professional Volleyball is opaque. We built this site to make it clearer for the
            athletes, coaches and parents who want to learn more about how the professional sport works,
            and how to get the best possible experience from it.
          </p>
        </div>

      </main>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
